services:
  - type: web
    name: jobboard
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobBoardProject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jobBoardProject.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: jobboard
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: jobboard-db
    plan: free
